apiVersion: batch/v1
kind: Job
metadata:
  generateName: openshift-job-cleaner-
spec:
  activeDeadlineSeconds: 300
  template:
    metadata:
      labels:
        parent: "openshift-job-cleaner"
        kind: "job"
    spec:
     activeDeadlineSeconds: 300
     serviceAccountName: openshift-job-cleaner
     volumes:
       - configMap:
           defaultMode: 420
           name: ojc.yml
         name: ojc-config-file
     containers:
     - name: openshift-job-cleaner
       image: docker-registry.nine.ch/ninech/openshift-job-cleaner:latest
       env:
         - name: SENTRY_DSN
           value: 'https://<key>:<secret>@sentry.io/<project>'
       volumeMounts:
         - mountPath: /opt/ojc/
           name: ojc-config-file
           readOnly: true
     restartPolicy: OnFailure




